// <auto-generated />
using System;
using JPS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JPS.Migrations.Bill
{
    [DbContext(typeof(BillContext))]
    partial class BillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JPS.Data.BillDatabaseModel", b =>
                {
                    b.Property<string>("bill_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cust_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date_generated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("premise_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bill_id");

                    b.ToTable("Bill_Information");
                });

            modelBuilder.Entity("JPS.Data.PREMISE_DETAILS", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("AS CONCAT(SUB_ID, CONVERT(NVARCHAR(90), ROW_ID)) PERSISTED");

                    b.Property<string>("LOCATION_NAME")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ROW_ID")
                        .IsRequired()
                        .HasColumnType("INT IDENTITY(200, 10)");

                    b.Property<string>("SUB_ID")
                        .HasColumnType("NVARCHAR(10) DEFAULT 'PREPJPS'");

                    b.HasKey("ID");

                    b.ToTable("PREMISE_DETAILS");
                });
#pragma warning restore 612, 618
        }
    }
}
